=== gioce90/TransferSimulation-JADE-Multi-agent-System/src/XmlParser/GoodsXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ROOT">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Goods" type="GoodsType" maxOccurs="unbounded"/>
			</xs:sequence>
	  		<xs:attribute name="buyerName" type="xs:string"/> 
		</xs:complexType>
	</xs:element>
	
	
	<xs:complexType name="GoodsType">
	  <xs:all>
	    <xs:element name="codice" type="xs:string" minOccurs="1">
			<!--<xs:key name="codice">
	    		<xs:selector xpath="."></xs:selector>
	    		<xs:field xpath="."></xs:field>
	    	</xs:key> -->
	    </xs:element>
	    <xs:element name="descrizione" type="xs:string" minOccurs="0"/>
	    <xs:element name="dimensione" type="xs:string" minOccurs="0"/>
	    <xs:element name="quantità" type="xs:float"/>
	    <xs:element name="volume" type="xs:double"/>
	    <xs:element name="tipo" type="xs:string" minOccurs="0"/>
	    <xs:element name="pericolosa" type="xs:boolean"/>
	    <xs:element name="locationStart" type="xs:string" minOccurs="0"/>
	    <xs:element name="locationEnd" type="xs:string" minOccurs="0"/>
	    <xs:element name="dateStart" type="xs:date" minOccurs="0"/>
	    <xs:element name="dateLimit" type="xs:int"/>
	    <xs:element name="necessità" type="xs:string" minOccurs="0"/>
	  </xs:all>
	</xs:complexType>
	
</xs:schema>

=== gioce90/TransferSimulation-JADE-Multi-agent-System/Buyer2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT buyerName="Buyer2"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="GoodsXMLSchema.xsd"> 

	
	<Goods>
		<codice>M002</codice>
		<descrizione>Petrolio</descrizione>
		<necessità>Cisterna</necessità>
		<dimensione>x*y*z</dimensione>
		<quantità>200.0</quantità>
		<volume>200.0</volume>
		<tipo>liquida</tipo>
		<pericolosa>true</pericolosa>
		<locationStart>Lecce</locationStart>
		<locationEnd>Bari</locationEnd>
		<dateStart>2015-04-29</dateStart>
		<dateLimit>4</dateLimit>
	</Goods>
	
	
	<Goods>
		<codice>M003</codice>
		<descrizione>Cibo refrigerato</descrizione>
		<necessità>Frigo</necessità>
		<dimensione>x*y*z</dimensione>
		<quantità>200.0</quantità>
		<volume>200.0</volume>
		<tipo>solida</tipo>
		<pericolosa>false</pericolosa>
		<locationStart>Barletta</locationStart>
		<locationEnd>Bari</locationEnd>
		<dateStart>2015-04-29</dateStart>
		<dateLimit>3</dateLimit>
	</Goods>
	

	
	
	<Goods>
		<codice>M005</codice>
		<descrizione>Pietra</descrizione>
		<necessità></necessità>
		
		<dimensione>x*y*z</dimensione>
		<quantità>150.0</quantità>
		<volume>200.0</volume>
		<tipo>solida</tipo>
		<pericolosa>false</pericolosa>
		
		<locationStart>Trani</locationStart>
		<locationEnd>Bari</locationEnd>
		
		<dateStart>2015-04-30</dateStart>
		<dateLimit>6</dateLimit>
	</Goods>
	
	
	<Goods>
		<codice>M006</codice>
		<descrizione>Olio</descrizione>
		<necessità>Cisterna</necessità>
		
		<dimensione>x*y*z</dimensione>
		<quantità>150.0</quantità>
		<volume>200.0</volume>
		<tipo>solida</tipo>
		<pericolosa>false</pericolosa>
		
		<locationStart>Bisceglie</locationStart>
		<locationEnd>Bari</locationEnd>
		
		<dateStart>2015-04-30</dateStart>
		<dateLimit>6</dateLimit>
	</Goods>
	
	
	
	
</ROOT>
