=== gioce90/TransferSimulation-JADE-Multi-agent-System/src/XmlParser/VehicleXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Fleet" type="FleetType"/>
	
	
	<xs:complexType name="FleetType">
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="Car" />
			<xs:element ref="Van" />
			<xs:element ref="Truck" />
			<xs:element ref="Trailer" />
			<xs:element ref="RoadTractor" />	
			<xs:element ref="SemiTrailer" />
			<xs:element ref="TrailerTruck" />
			<xs:element ref="SemiTrailerTruck" />
		</xs:choice>
		<xs:attribute name="shipperName" type="xs:string"/>
	</xs:complexType>
	
	
	<xs:complexType name="VehicleType" abstract="true">
		<xs:sequence minOccurs="0">
			<xs:element name="plate" type="xs:string" minOccurs="1" />
			<xs:element name="mark" type="xs:string" minOccurs="1" />
			<xs:element name="model" type="xs:string" minOccurs="1" />
			<xs:element name="trim" type="xs:string" minOccurs="0" />
			<xs:element name="allestimento" type="xs:string" minOccurs="0" />
			<xs:element name="stato" type="State" minOccurs="1"/>
			<xs:element name="carryingCapacity" type="xs:float" minOccurs="0" />
			<xs:element name="ptt" type="xs:float" minOccurs="0" />
			<xs:element name="weight" type="xs:float" minOccurs="0" />
			<xs:element name="volume" type="xs:float" minOccurs="0" />
			<xs:element name="length" type="xs:float" minOccurs="0" />
			<xs:element name="height" type="xs:float" minOccurs="0" />
			<xs:element name="width" type="xs:float" minOccurs="0" />
			<xs:element name="locazioneAttuale" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	



	<!-- Definizioni: SimpleVehicle e ComplexVehicle -->
	
	<xs:complexType name="SimpleVehicle">
		<xs:complexContent>
			<xs:extension base="VehicleType">
				<xs:attribute name="id" type="xs:ID"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ComplexVehicle">
		<xs:complexContent>
			<xs:extension base="VehicleType">
				<xs:attribute name="refid" type="xs:IDREF"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	
	
	
	<!-- Definizione tipi Car, Van, Truck, Trailer, RoadTractor, SemiTrailer -->
	
	<xs:element name="Car" type="SimpleVehicle" >
		<xs:key name="idd" id="idC">
			<xs:selector xpath="."></xs:selector>
			<xs:field xpath="plate"></xs:field>
		</xs:key>
	</xs:element>
	
	<xs:element name="Van" type="SimpleVehicle"/>
	
	<xs:element name="Truck" type="SimpleVehicle"/>
	
	<xs:element name="Trailer" type="SimpleVehicle"/>
	
	<xs:element name="RoadTractor" type="SimpleVehicle"/>
	
	<xs:element name="SemiTrailer" type="SimpleVehicle"/>
	
	
	
	
	<!-- Definizione tipo TrailerTruck (autotreno) -->

	<xs:group name="DrivingPart">
		<xs:choice>
			<xs:element name="Car" type="ComplexVehicle">
				<xs:keyref name="ke" refer="idd" id="d"> <xs:selector xpath="." > </xs:selector><xs:field xpath="."></xs:field></xs:keyref>
			</xs:element>
			<xs:element name="Van" type="ComplexVehicle"/>
			<xs:element name="Truck" type="ComplexVehicle"/>
		</xs:choice>
	</xs:group>
	
	<xs:element name="TrailerTruck">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="DrivingPart" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Trailer" type="ComplexVehicle" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>




	<!-- Definizione tipo SemiTrailerTruck (autoarticolato) -->
	
	<xs:element name="SemiTrailerTruck">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RoadTractor" type="ComplexVehicle" minOccurs="1" maxOccurs="1"/>
				<xs:element name="SemiTrailer" type="ComplexVehicle" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>




	<!-- Altre definizioni -->

	<xs:simpleType name="State">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DISPONIBILE"/>
			<xs:enumeration value="NON_DISPONIBILE"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== gioce90/TransferSimulation-JADE-Multi-agent-System/Input di esempio/Shipper2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Fleet shipperName="Shipper2"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="VehicleXMLSchema.xsd"> 

	
	<Car id="car2">
		<plate>BBB</plate>
		<mark>Volkwagen</mark>
		<model>M1</model>
		<trim></trim>
		<allestimento></allestimento>
		<stato>NON_DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>2</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Bari</locazioneAttuale>
	</Car>
	
	
	<Truck id="truck1">
		<plate>DDD</plate>
		<mark>Scania</mark>
		<model>M3</model>
		<trim></trim>
		<allestimento>Cisterna</allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>1.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>2.0</weight>
		<volume>3.0</volume>
		<length>4.0</length>
		<height>5.0</height>
		<width>6.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</Truck>
	
	
	<Trailer id="trailer1">
		<plate>EEE</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>NON_DISPONIBILE</stato>
		<carryingCapacity>6.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>7.0</weight>
		<volume>8.0</volume>
		<length>9.0</length>
		<height>1.0</height>
		<width>2.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</Trailer>
	
	
	<RoadTractor id="roadtractor1">
		<plate>FFF</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento></allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</RoadTractor>
	
	
	<SemiTrailer id="semitrailer1">
		<plate>GGG</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</SemiTrailer>
	
	
	<TrailerTruck id="trailerTruck1">
		<Car refid="car1"/>
		<Trailer refid="trailer1"/>
	</TrailerTruck>
	
	
	<SemiTrailerTruck id="semiTrailerTruck1">
		<RoadTractor refid="roadtractor1"/>
		<SemiTrailer refid="semitrailer1"/>
	</SemiTrailerTruck>
	
	
</Fleet>

=== gioce90/TransferSimulation-JADE-Multi-agent-System/src/XmlParser/Shipper1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Fleet shipperName="Shipper1"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="VehicleXMLSchema.xsd"> 

	<Car id="car1">
		<plate>AAA</plate>
		<mark>Peugeot</mark>
		<model>206</model>
		<trim></trim>
		<allestimento></allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>2</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Bari</locazioneAttuale>
	</Car>
	
	<Van id="van1">
		<plate>CCC</plate>
		<mark>Volvo</mark>
		<model></model>
		<trim></trim>
		<allestimento>frigorifero</allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>3</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Barletta</locazioneAttuale>
	</Van>
	
	<Truck id="truck1">
		<plate>DDD</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</Truck>
	
	<Trailer id="trailer1">
		<plate>EEE</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>NON_DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</Trailer>
	
	<RoadTractor id="roadtractor1">
		<plate>FFF</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>NON_DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</RoadTractor>
	
	<SemiTrailer id="semitrailer1">
		<plate>GGG</plate>
		<mark>Scania</mark>
		<model></model>
		<trim></trim>
		<allestimento>Frigo</allestimento>
		<stato>NON_DISPONIBILE</stato>
		<carryingCapacity>0.0</carryingCapacity>
		<ptt>5</ptt>
		<weight>0.0</weight>
		<volume>0.0</volume>
		<length>0.0</length>
		<height>0.0</height>
		<width>0.0</width>
		<locazioneAttuale>Andria</locazioneAttuale>
	</SemiTrailer>
	
	
	<TrailerTruck id="trailerTruck1">
		<Car refid="trailer1"/>
		<Trailer refid="car1"/>
	</TrailerTruck>
	
 
	<SemiTrailerTruck>
		<RoadTractor refid="car1"/>
		<SemiTrailer refid="semitrailer1"/>
	</SemiTrailerTruck>
	
	
</Fleet>
